### ISSUE TITLE
OPAQUE data length is incorrectly calculated

### ISSUE THREAD

**Issue by cearny** [clncln1/node-aswbxml#2]
As per https://www.w3.org/1999/06/NOTE-wbxml-19990624/#_Toc443384897 the length of an opaque data segment is not a UINT32 big-endian, but a mb_u_int32, which is a multi-byte encoding of an unsigned integer.

This also comes into play for other fields as well (charset for example), but it chiefly affects the parsing of OPAQUE data segments for e-mails, for example.

I've opened a pull request to implement a mb_u_int32 parser (inspired from Horde) that should fix that problem.

**Comment by clncln1** [comment]
Thanks, landed in 0.0.5
